name: geo_ad
description: "Geo-Ad learning version: sign in, fake OTP, and a map of all ads."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.18.1
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
